name: mynew-file

on: push

jobs:
  mynew-file:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      -name: Checkout code
      uses: actions/checkout@v2
      
      -name: Run mynew-file
       uses: github/mynew-file@v3
       env:
         DEFAULT_BRANCH: main
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
